/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrawlBrawlIdRouteImport } from './routes/brawl/$brawlId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrawlBrawlIdRoute = BrawlBrawlIdRouteImport.update({
  id: '/brawl/$brawlId',
  path: '/brawl/$brawlId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brawl/$brawlId': typeof BrawlBrawlIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brawl/$brawlId': typeof BrawlBrawlIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brawl/$brawlId': typeof BrawlBrawlIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brawl/$brawlId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brawl/$brawlId'
  id: '__root__' | '/' | '/brawl/$brawlId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrawlBrawlIdRoute: typeof BrawlBrawlIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brawl/$brawlId': {
      id: '/brawl/$brawlId'
      path: '/brawl/$brawlId'
      fullPath: '/brawl/$brawlId'
      preLoaderRoute: typeof BrawlBrawlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrawlBrawlIdRoute: BrawlBrawlIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
